spring:
  application:
    name: variant-service

server:
  port: 8089

logging:
  level:
    root: error

debug: true

grpc:
  server:
    port: 4049
  client:
    inventory-client:
      address: static://localhost:4050
      negotiationType: PLAINTEXT

kafka-topic:
  variant-create: variant-create
  variant-delete: variant-delete
