spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers:
      - localhost:29092    
  data:
    mongodb:
      uri: mongodb://developer:password123@localhost:27017/variantdb?authSource=admin

  
    
