spring:
  application:
    name: variant-service
  data:
    mongodb:
      uri: mongodb://developer:password123@localhost:27017/variantdb?authSource=admin
grpc:
  server:
    port: 4049
server:
  port: 8089
