spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://developer:password123@mongodb:27017/variantdb?authSource=admin
  kafka:
    bootstrap-servers:
      - kafka:9092
