spring:
  application:
    name: variant-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
      group-id: variant-group
      enable-auto-commit: true

server:
  port: 8089

grpc:
  server:
    port: 4049
  client:
    inventory-client:
      address: static://localhost:4050
      negotiationType: PLAINTEXT

kafka-topic:
  variant-create: variant-create
  variant-delete: variant-delete
