server:
  port: 8080
  servlet:
    context-path:
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:8080

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude:
      - net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    bootstrap-servers:
      - ${BOOTSTRAP-SERVER}
  data:
    redis:
      host: localhost
      port: 6379
grpc:
  client:
    profile-client:
      address: static://localhost:4048
      negotiationType: PLAINTEXT

uri: ${URI-ISSUER}

rsa:
  public-key: ${RSA-PUBLIC-KEY}
  private-key: ${RSA-PRIVATE-KEY}

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

openApi:
  uri: ${URI-OPENAPI}
