services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
    networks:
      - E_COMMERCE_PLATFORM-net  

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: E_COMMERCE_PLATFORM_AUTH
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - E_COMMERCE_PLATFORM-net

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - E_COMMERCE_PLATFORM-net

volumes:
  mongodb_data:
  pgdata:

networks:
  E_COMMERCE_PLATFORM-net:
    external: true
