version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: E_COMMERCE_PLATFORM_AUTH
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - E_COMMERCE_PLATFORM-net

volumes:
  pgdata:

networks:
  E_COMMERCE_PLATFORM-net:
    external: true
