version: '3.8'

services:
  keycloak:
    image: bitnami/keycloak:24
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: E_COMMERCE_PLATFORM_AUTH
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: 123456
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - E_COMMERCE_PLATFORM-net

networks:
  E_COMMERCE_PLATFORM-net:
    external: true
