server:
  port: 4000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**
              filters:
                - name: JwtValidation
                  args:
                    enabled: true
                    skippedRoutes:
                      - "POST:/auth/login"
                      - "POST:/auth/register"

            - id: product-router
              uri: http://localhost:8083
              predicates:
                - Path=/products/**
              filters:
                - StripPrefix=1

            - id: product-service-api-docs
              uri: http://localhost:8083
              predicates:
                - Path=-docs/product-service
              filters:
                - RewritePath=-docs/product-service, /v3-docs

            - id: product-coordinator-router
              uri: http://localhost:8042
              predicates:
                - Path=/product-coordinator/**
              filters:
                - StripPrefix=1

            - id: product-coordinator-service-api-docs
              uri: http://localhost:8042
              predicates:
                - Path=-docs/product-coordinator-service
              filters:
                - RewritePath=-docs/product-coordinator-service, /v3-docs

            - id: variant-router
              uri: http://localhost:8089
              predicates:
                - Path=/variants/**
              filters:
                - StripPrefix=1

            - id: variant-service-api-docs
              uri: http://localhost:8089
              predicates:
                - Path=-docs/variant-service
              filters:
                - RewritePath=-docs/variant-service, /v3-docs

auth:
  service:
    url: http://localhost:8080
