server:
  port: 4000

spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: dwmORnygbddyMJqbWfm+Jg==
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:4000/login/oauth2/code/gateway-client"

        provider:
          my-provider:
            issuer-uri: http://localhost:8080
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**
              filters:

            - id: product-router
              uri: http://localhost:8083
              predicates:
                - Path=/products/**
              filters:
                - TokenRelay=

            - id: product-service-api-docs
              uri: http://localhost:8083
              predicates:
                - Path=-docs/product-service
              filters:
                - RewritePath=-docs/product-service, /v3-docs

            - id: variant-router
              uri: http://localhost:8089
              predicates:
                - Path=/variants/**
              filters:
                - StripPrefix=1

            - id: variant-service-api-docs
              uri: http://localhost:8089
              predicates:
                - Path=-docs/variant-service
              filters:
                - RewritePath=-docs/variant-service, /v3-docs

auth:
  service:
    url: http://localhost:8080
