server:
  port: 4000

spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client-id
            client-secret: dwmORnygbddyMJqbWfm+Jg==
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:4000/login/oauth2/code/gateway-client"
        provider:
          my-provider:
            issuer-uri: http://auth-service:8080

      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8080

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8080
          predicates:
            - Path=/auth/**
          filters: []

        - id: auth-service-swagger
          uri: http://auth-service:8080
          predicates:
            - Path=/swagger/auth-service/**
          filters:
            - RewritePath=/swagger/auth-service/(?<path>.*), /$\{path}

        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=/api/orders/**
          filters: []

        - id: order-service-swagger
          uri: http://order-service:8084
          predicates:
            - Path=/swagger/order-service/**
          filters:
            - RewritePath=/swagger/order-service/(?<path>.*), /$\{path}

        - id: notification-service
          uri: http://notification-service:8092
          predicates:
            - Path=/notifications/**
          filters: []

        - id: notification-service-swagger
          uri: http://notification-service:8092
          predicates:
            - Path=/swagger/notification-service/**
          filters:
            - RewritePath=/swagger/notification-service/(?<path>.*), /$\{path}

        - id: product-router
          uri: http://product-service:8083
          predicates:
            - Path=/products/**
          filters:
            - TokenRelay

        - id: product-service-swagger
          uri: http://product-service:8083
          predicates:
            - Path=/swagger/product-service/**
          filters:
            - RewritePath=/swagger/product-service/(?<path>.*), /$\{path}

        - id: variant-router
          uri: http://variant-service:8089
          predicates:
            - Path=/variants/**
          filters: []

        - id: variant-service-swagger
          uri: http://variant-service:8089
          predicates:
            - Path=/swagger/variant-service/**
          filters:
            - RewritePath=/swagger/variant-service/(?<path>.*), /${path}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    urls:
      - name: auth-service
        url: /swagger/auth-service/v3/api-docs
      - name: product-service
        url: /swagger/product-service/v3/api-docs
      - name: variant-service
        url: /swagger/variant-service/v3/api-docs
      - name: order-service
        url: /swagger/order-service/v3/api-docs
      - name: notification-service
        url: /swagger/notification-service/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
