
services:
  product-service:
    build: .
    image: product-service:latest
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb://developer:password123@mongodb:27017/productdb?authSource=admin
      - KAFKA_URI=kafka:9092
      - URI-ISSUER=http://auth-service:8080 
    expose:
      - "8083"
      - "4043"
    networks:
      - E_COMMERCE_PLATFORM-net

networks:
  E_COMMERCE_PLATFORM-net:
    external: true # Docker Compose sẽ không tạo mới mạng này, mà sẽ xài lại một cái mạng đã được tạo từ trước ở ngoài (bên ngoài file docker-compose.yml).
