spring:
  config:
    activate:
      on-profile:
        - local
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers:
      - localhost:29092      

cloudinary:
  apiKey: ${API_CLOUD_KEY}
  apiSecret: ${API_CLOUD_SECRET}
  cloudName: ${API_CLOUD_NAME}
  maxFileSize: ${MAX_FILE_SIZE}
  allowedMimeTypes:
    - image/png
    - image/jpeg
    - image/jpg
