spring:
  application:
    name: cloud-service

server:
  port: 8081

cloudinary:
  apiKey: 863938529749295
  apiSecret: ezwBvkmvEwE7ZzquiJ35gNQW2PU
  cloudName: dxpyuj1mm
  maxFileSize: 55242880
  allowedMimeTypes:
    - image/png
    - image/jpeg
    - image/jpg
