spring:
  application:
    name: billing-service
  grpc:
    server:
      port: 4040
      enable-http2: true
logging:
  level:
    org.springframework.grpc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    io.grpc: INFO
server:
  port: 8085
grpc:
  server:
    port: 4040
    enable-http2: true
