  
services:
  variant-service:
    build: .
    image: variant-service:latest
    container_name: variant-service
    expose: 
      - "8089"
      - "4049" 
    networks:
      - E_COMMERCE_PLATFORM-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker  
networks:
  E_COMMERCE_PLATFORM-net:
    external: true      