  
services:
  variant-service:
    build: .
    image: variant-service:latest
    container_name: variant-service
    expose: 
      - "8089"
      - "4049" 
    networks:
      - E_COMMERCE_PLATFORM-net
    environment:
      - MONGO-URI=mongodb://developer:password123@mongodb:27017/variantdb?authSource=admin  
      - URI-OPENAPI=http://localhost:4000
      - ISSUER-URI=http://auth-service:8080
      - KAFKA-URI=kafka:9092
      - GRPC-INVENTORY=static://inventory-service:4050
      - GRPC-PRODUCT=static://product-service:4043
networks:
  E_COMMERCE_PLATFORM-net:
    external: true      