server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI} # đọc từ biến môi trường hoặc Vault

  # kafka:
  #   bootstrap-servers: ${KAFKA_SERVERS}
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

grpc:
  client:
    variant-client:
      address: static://${GRPC_VARIANT_ADDR}
      negotiationType: TLS
