server:
  port: 8083

spring:
  application:
    name: product-service
  servlet:
    multipart:
      enabled: true
      strict-servlet-compliance: true
      max-file-size: 10MB
      max-request-size: 20MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

logging:
  level:
    root: debug

grpc:
  server:
    port: 4043
  client:
    variant-client:
      address: static://localhost:4049
      negotiationType: PLAINTEXT
    cloud-client:
      address: static://localhost:4041
      negotiationType: PLAINTEXT

cloudinary:
  resourceFile: image
  assetFolder: products
