spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://developer:password123@localhost:27017/productdb?authSource=admin
  servlet:
    multipart:
      enabled: true
      strict-servlet-compliance: true

grpc:
  client:
    variant-client:
      address: static://localhost:4049
      negotiationType: PLAINTEXT

server:
  port: 8083
