server:
  port: 8083

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://developer:password123@mongodb:27017/productdb?authSource=admin
  servlet:
    multipart:
      enabled: true
      strict-servlet-compliance: true
  # kafka:
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.SpringSerializer
  #     value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  #   bootstrap-servers:
  #     - localhost:29092

grpc:
  server:
    port: 4043
  client:
    variant-client:
      address: static://localhost:4049
      negotiationType: PLAINTEXT
    cloud-client:
      address: static://localhost:4041
      negotiationType: PLAINTEXT
