server:
  port: 8083

spring:
  application:
    name: product-service
  servlet:
    multipart:
      enabled: true
      strict-servlet-compliance: true
      
grpc:
  server:
    port: 4043
  client:
    variant-client:
      address: static://localhost:4049
      negotiationType: PLAINTEXT
    cloud-client:
      address: static://localhost:4041
      negotiationType: PLAINTEXT
