version: '3.8'

services:
  attribute-service:
    image: attribute-service:latest
    container_name: attribute-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - MONGODB_URI=mongodb://adminAttribute:admin123@localhost:27017/attributedb?authSource=admin
      - PORT=8082

    networks:
      - E_COMMERCE_NETWORK
      