spring:
  profiles:
    active:
      - local
  datasource:
    url: jdbc:postgresql://postgres:5432/e_commerce_platform_inventory
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
