spring:
  application:
    name: attribute-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${URI-ISSUER}

grpc:
  server:
    port: 4042

server:
  port: 8082
