server:
  port: 8094
spring:
  application:
    name: email-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER-URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ninh56099@gmail.com
    password: oaue lupz slae bzsi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      group-id: email-group
      bootstrap-servers: ${BOOTSTRAP-SERVER}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
