
services:
  inventory-service:
    build: .
    image: inventory-service:latest
    container_name: inventory-service
    expose: 
      - "8090"
      - "4050" 
    environment:
    - SPRING_PROFILES_ACTIVE=docker  
    networks:
      - E_COMMERCE_PLATFORM-net
networks:
  E_COMMERCE_PLATFORM-net:
    external: true      