
services:
  inventory-service:
    build: .
    image: inventory-service:latest
    container_name: inventory-service
    expose: 
      - "8090"
      - "4050" 
    environment:
    - KAFKA-URI=kafka:9092
    - POSTGRES-URI=jdbc:postgresql://postgres:5432/e_commerce_platform_inventory
    networks:
      - E_COMMERCE_PLATFORM-net
networks:
  E_COMMERCE_PLATFORM-net:
    external: true      