server:
  port: 8042

spring:
  application:
    name: product-coordinator-service

grpc:
  client:
    cloud-client:
      address: static://localhost:4041
      negotiationType: PLAINTEXT
    product-client:
      address: static://localhost:4043
      negotiationType: PLAINTEXT
    variant-client:
      address: static://localhost:4049
      negotiationType: PLAINTEXT

cloudinary:
  resourceFile: image
  assetFolder: products
